### ISSUE TITLE
Parser doesn't work on bbc

### ISSUE THREAD

**Issue by vtechguys** [fmacpro/horseman-article-parser#47]
I have used parser on bbc articles but it doesn't work on those 
![Screen Shot 2020-11-26 at 11 11 36 AM](https://user-images.githubusercontent.com/29702340/100312431-5034a180-2fd8-11eb-9622-740f475a5478.png)

Article link: https://www.bbc.com/news/health-55040635

I have tried on bbc article it looks like it only picks up title text, it will be really helpful if I can parse that.

**Comment by agatlin** [comment]
I tested the BBS URL also and got the same result. I was able to view the content within Chrome, but it did not return content in the article parser. 

Apparently, these folks are trying to be a little tricky. Here is the HTML from the first two paragraphs.

```
<div data-component="text-block" class="css-uf6wea-RichTextComponentWrapper e1xue1i83">
   <div class="css-83cqas-RichTextContainer e5tfeyi2">
      <p><b class="css-14iz86j-BoldText e5tfeyi0">The coronavirus vaccine developed by the University of Oxford is highly effective at stopping people developing Covid-19 symptoms, a large trial shows. </b></p>
   </div>
</div>

<div data-component="text-block" class="css-uf6wea-RichTextComponentWrapper e1xue1i83">
   <div class="css-83cqas-RichTextContainer e5tfeyi2">
      <p>Interim data suggests 70% protection, but the researchers say the figure may be as high as 90% by tweaking the dose. </p>
   </div>
</div>
```

As you can see, they are wrapping each paragraph in two divs which is a bit odd, and it is obviously throwing of the article parser. This is probably a fairly easy fix.

**Comment by vtechguys** [comment]
I am not sure but I think the regex matching this lib using is eliminating content from the bbc, main content area on the site is wrapped in a div with `class="css-16rg7hm-ContainerWithSidebarWrapper e1jl38b40" ` and it matches for regex `'sidebar'` so it is getting removed as seen here in the [code](https://github.com/fmacpro/horseman-article-parser/blob/28d204f407b0f8a622eb0768bf221d5f77be8c6d/helpers.js#L175), I think this is why scraper does not work on bbc.
